spring:
  application:
    name: api-gateway

server:
  port: 9002

  # routes to serviceId
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-a
    api-b:
      path: /api-b/**
      serviceId: service-b

  # routes to url
  #zuul.routes.api-a-url.path=/api-a-url/**
  #zuul.routes.api-a-url.url=http://localhost:2222/

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/